language: node_js
node_js:
- '0.10'
install:
- sudo apt-get update -qq
deploy:
  provider: heroku
  api_key:
    secure: MKdtah0spGq6va0zHQnjzt+Km5Xf6ZwtOodigzMqpobu2yKEemBe/+H6gL9hf4l7P6r1KGcTXh6uayAezUEsdeGSv66VK9GwI8eS8UgMGI7uk/yhUKAB6CTiPbcv7KvImgHWHMSNxh/qav0U8CHKDTc/JclvqepoGvfdbo8Ch8A=
  app: sheltered-reef-5921
  on:
    repo: taka011239/slack_bot
notifications:
  hipchat:
    rooms:
      secure: SAy+/uHGrqc2Bz8qFT9BENyj5gl3RkPmMnCc74nK6Lo4mz9PnChMsRbboTDcv3gVSzASsvSb2BmuY+HGOR/7sAop5C0irou2CvO7tRyAysUU9vDxpRujxnTwwh2RMX5tG4yeeAjrOOPXMNU/mimpyVxG/wjAWUEJ9r9AEM6ZDpE=
      template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
